use_frameworks!

platform :ios, '9.0'

target 'LSJHNavBar_Example' do
  pod 'LSJHNavBar', :path => '../'

  target 'LSJHNavBar_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
